HUMAN_STAMPS_COMPLETE = (0, 128, 0)
HUMAN_PAGES_COMPLETE = (255, 165, 0)
MACHINE_STAMPS_COMPLETE = (0, 255, 255)
MACHINE_PAGES_COMPLETE = (0, 153, 255)
PENDING = (0, 0, 0)
color_code = (HUMAN_STAMPS_COMPLETE, HUMAN_PAGES_COMPLETE, MACHINE_STAMPS_COMPLETE, MACHINE_PAGES_COMPLETE, PENDING)

NEW_ANNOTATIONS_INPUT_FOLDER = "/var/www/html/LabelMeAnnotationTool/labelme_input_folder"
LABELME_ROOT_DIR = "/var/www/html/LabelMeAnnotationTool"
DATASET_NAME = "Stamps"
IMAGES_DIR_PATH = LABELME_ROOT_DIR + "/Images/" + DATASET_NAME
ANNOTATIONS_DIR_PATH = LABELME_ROOT_DIR + "/Annotations/" + DATASET_NAME

MACHINE_LABELED_STAMPS_PREFIX = "mls_"
MACHINE_LABELED_PAGES_PREFIX = "mlp_"
HUMAN_LABELED_STAMPS_PREFIX = "hls_"
HUMAN_LABELED_PAGES_PREFIX = "hlp_"
