HUMAN_STAMPS_COMPLETE = (0, 128, 0)
HUMAN_PAGES_COMPLETE = (255, 165, 0)
MACHINE_STAMPS_COMPLETE = (0, 255, 255)
MACHINE_PAGES_COMPLETE = (0, 153, 255)
PENDING = (0, 0, 0)
color_code = (HUMAN_STAMPS_COMPLETE, HUMAN_PAGES_COMPLETE, MACHINE_STAMPS_COMPLETE, MACHINE_PAGES_COMPLETE, PENDING)

IMAGES_DIR_PATH = "/Users/juran/Downloads/unsamples"
