# Generated by Django 3.0.2 on 2020-01-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.CharField(max_length=200)),
                ('human_labeled_stamps', models.BooleanField(default=False)),
                ('human_labeled_pages', models.BooleanField(default=False)),
                ('machine_labeled_stamps', models.BooleanField(default=False)),
                ('machine_labeled_pages', models.BooleanField(default=False)),
            ],
        ),
    ]
