# Generated by Django 3.0.2 on 2020-01-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file_name', models.CharField(max_length=200)),
                ('human_stamps_complete', models.BooleanField(default=False)),
                ('human_pages_complete', models.BooleanField(default=False)),
                ('machine_stamps_complete', models.BooleanField(default=False)),
                ('machine_pages_complete', models.BooleanField(default=False)),
            ],
        ),
    ]
