# Generated by Django 3.0.2 on 2020-02-15 15:54
import os

from django.core import serializers
from django.db import migrations, models

fixture_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../fixtures'))
fixture_filename = 'stages.json'


def load_fixture(apps, schema_editor):
    fixture_file = os.path.join(fixture_dir, fixture_filename)

    fixture = open(fixture_file, 'rb')
    objects = serializers.deserialize('json', fixture, ignorenonexistent=True)
    for obj in objects:
        obj.save()
    fixture.close()


def unload_fixture(apps, schema_editor):
    "Brutally deleting all entries for this model..."

    MyModel = apps.get_model("labelMeNav", "Stage")
    MyModel.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('labelMeNav', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.RunPython(load_fixture, reverse_code=unload_fixture),
    ]
