# Generated by Django 3.0.2 on 2020-02-15 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labelMeNav', '0002_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='stage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='labelMeNav.Stage'),
            preserve_default=False,
        ),
    ]
