# Generated by Django 3.0.2 on 2020-01-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('verified', models.BooleanField(default=False)),
                ('human_tagged', models.BooleanField(default=False)),
                ('model_tagged', models.BooleanField(default=False)),
                ('pending', models.BooleanField(default=True)),
            ],
        ),
    ]
